
name: Deploy to GitHub Pages
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: "20"
      - run: npm install
      - run: npx nuxt build --preset github_pages
        env:
          NUXT_APP_BASE_URL: /nuxt-app/   # 👈 改成你的仓库名
      - uses: actions/upload-pages-artifact@v5
        with:
          path: ./.output/public
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4